#ifndef CHANNELS_H
#define CHANNELS_H

#define CHANNEL_TYPE_BOOLEAN_R 0x80
#define CHANNEL_TYPE_BOOLEAN_W 0x40

#define CHANNEL_TYPE_BYTE_R 0x81
#define CHANNEL_TYPE_BYTE_W 0x41

#define CHANNEL_TYPE_SHORT_R 0x82
#define CHANNEL_TYPE_SHORT_W 0x42

#define CHANNEL_TYPE_INT_R 0x83
#define CHANNEL_TYPE_INT_W 0x43

#define CHANNEL_TYPE_FLOAT_R 0x84
#define CHANNEL_TYPE_FLOAT_W 0x44

#endif
